### ISSUE TITLE
wrong coil definition

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/coil_simulation_web#24]
command:

```
python coil_simulation.py -rada 10 -radb 5 -r 3 -c 5 -o b1map.png -o1 coils.png -definition 20 -orientation 1 -slice 0 -type 2 -preset 1 -radc 3
```

result:
![screen shot 2015-12-07 at 16 07 20](https://cloud.githubusercontent.com/assets/2482071/11639763/ba443c4e-9cfc-11e5-8097-051909a7ca9c.png)

![screen shot 2015-12-07 at 16 07 15](https://cloud.githubusercontent.com/assets/2482071/11639768/bdcc47b2-9cfc-11e5-96ad-fd0fd13041fe.png)

**Comment by Claudelb** [comment]
![figure_1](https://cloud.githubusercontent.com/assets/14129776/11664467/f1b066a4-9daf-11e5-8bcc-b1373c2e0fdc.png)

fixed! Horray!
